---
title: "Grid Agent-Based Models"
description: |
  This article runs you through using the `gridabm` library to play around with 2D cellular automata or grid ABMs.
author:
  - name: Johannes Nakayama 
    url: https://github.com/JohannesNakayama
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(gridabm)
library(ggplot2)
```

```{r, echo=TRUE}
forest <- create_forest(20, 0.8)
forest_results <- run_automaton(forest, 100, forest_fire_step)
animate_model_run(forest_results, 5, c("white", "green", "red", "firebrick"))
```


```{r, echo=TRUE}
life_board <- matrix(
  sample(c(0, 1), prob = c(0.8, 0.2), replace = TRUE, size = 625),
  nrow = 25, ncol = 25
)
life_results <- run_automaton(life_board, 100, life_step)
animate_model_run(life_results, 4, c("white", "black"))
```


```{r, echo=TRUE}
schelling_board <- matrix(
  sample(c(0, 1, 2), prob = c(0.1, 0.45, 0.45), replace = TRUE, size = 400),
  nrow = 20, ncol = 20
)
schelling_results <- run_automaton(schelling_board, 100, schelling_step, tolerance = 3)
animate_model_run(schelling_results, 5, c("white", "orange", "blue"))
```


```{r, echo=TRUE}
brians_brain_board <- matrix(
  sample(c(0, 1, 2), prob = c(0.5, 0.25, 0.25), replace = TRUE, size = 2500),
  nrow = 50, ncol = 50
)
brians_brain_results <- run_automaton(brians_brain_board, 100, brians_brain_step)
animate_model_run(brians_brain_results, 2, c("black", "white", "blue")) +
  theme(
    plot.background = element_rect(fill = "black"),
    panel.background = element_rect(fill = "black"),
    panel.grid.major = element_line(color = "black"),
    panel.grid.minor = element_line(color = "black")
  )
```


